# Generated by Django 3.1.3 on 2020-11-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
    ]
